// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyFbQU6BKEg6aSxbO6R1I81NbBdFolIsM',
    appId: '1:576554626292:web:87ed5fbe3cd3549c6902a1',
    messagingSenderId: '576554626292',
    projectId: 'chatapplication-bce9d',
    authDomain: 'chatapplication-bce9d.firebaseapp.com',
    storageBucket: 'chatapplication-bce9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELoX9pF9FYvNi3fKm8YxNLFgOyKqwxL0',
    appId: '1:576554626292:android:406418db43c9362f6902a1',
    messagingSenderId: '576554626292',
    projectId: 'chatapplication-bce9d',
    storageBucket: 'chatapplication-bce9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8Q7SPy9MVrujtsx98DbGQIRoGEK97Tk',
    appId: '1:576554626292:ios:9f7c9792d26edc846902a1',
    messagingSenderId: '576554626292',
    projectId: 'chatapplication-bce9d',
    storageBucket: 'chatapplication-bce9d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa8Q7SPy9MVrujtsx98DbGQIRoGEK97Tk',
    appId: '1:576554626292:ios:9f7c9792d26edc846902a1',
    messagingSenderId: '576554626292',
    projectId: 'chatapplication-bce9d',
    storageBucket: 'chatapplication-bce9d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyFbQU6BKEg6aSxbO6R1I81NbBdFolIsM',
    appId: '1:576554626292:web:b86eefe435bd3b416902a1',
    messagingSenderId: '576554626292',
    projectId: 'chatapplication-bce9d',
    authDomain: 'chatapplication-bce9d.firebaseapp.com',
    storageBucket: 'chatapplication-bce9d.firebasestorage.app',
  );
}
